// qlever-sys: raw FFI bindings for the QLever C shim.
//
// These are unsafe, low-level bindings generated by bindgen.  Most users
// should use the `qlever` crate instead, which provides a safe Rust API.
//
// # Safety
//
// All functions in this module are `unsafe` because they call into C++ code:
//
// * Passing NULL pointers for parameters documented as non-null is undefined
//   behaviour.
// * `QleverHandle` must not be used from multiple threads simultaneously
//   without external synchronisation (the underlying C++ Qlever engine uses
//   a thread-safe result cache, but the handle itself is not `Send`/`Sync` by
//   default).  The safe `qlever` wrapper handles this correctly.

// Include the bindgen-generated bindings.
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(test)]
mod ffi_smoke_tests {
    use super::*;
    use std::ffi::CString;

    /// Verify that `qlever_version` returns a non-empty, valid UTF-8 string.
    #[test]
    fn version_is_non_empty() {
        let version_ptr = unsafe { qlever_version() };
        assert!(!version_ptr.is_null(), "qlever_version returned NULL");
        let version = unsafe { std::ffi::CStr::from_ptr(version_ptr) }
            .to_str()
            .expect("version is not valid UTF-8");
        assert!(!version.is_empty(), "version string is empty");
    }

    /// Verify that `qlever_last_error` returns a valid (possibly empty) string
    /// even when no error has occurred.
    #[test]
    fn last_error_is_always_valid() {
        let err_ptr = unsafe { qlever_last_error() };
        assert!(!err_ptr.is_null());
        // Must be valid UTF-8 / NUL-terminated.
        let _ = unsafe { std::ffi::CStr::from_ptr(err_ptr) }
            .to_str()
            .expect("last_error is not valid UTF-8");
    }

    /// Verify that passing NULL to `qlever_build_index` sets an error and
    /// returns a non-zero status code.
    #[test]
    fn build_index_null_args_returns_error() {
        let rc = unsafe { qlever_build_index(std::ptr::null(), std::ptr::null(), 0.0) };
        assert_ne!(rc, 0, "expected error for NULL args");
        let err_ptr = unsafe { qlever_last_error() };
        let err = unsafe { std::ffi::CStr::from_ptr(err_ptr) }
            .to_str()
            .unwrap();
        assert!(!err.is_empty(), "expected a non-empty error message");
    }

    /// Verify that passing NULL to `qlever_create` sets an error and returns
    /// NULL.
    #[test]
    fn create_null_base_name_returns_null() {
        let handle = unsafe { qlever_create(std::ptr::null(), 0.0, 0) };
        assert!(handle.is_null(), "expected NULL handle for NULL base_name");
        let err = unsafe {
            std::ffi::CStr::from_ptr(qlever_last_error())
                .to_str()
                .unwrap()
                .to_owned()
        };
        assert!(!err.is_empty());
    }

    /// Verify that `qlever_free_string` does not crash on a heap-allocated
    /// C string returned by `qlever_query`.  We cannot actually run a query
    /// in a unit test (no index on disk), but we verify the function is
    /// callable and that passing NULL is safe (it should just call free(NULL)).
    #[test]
    fn free_string_null_is_safe() {
        unsafe { qlever_free_string(std::ptr::null_mut()) };
    }
}
